server:
  port: 8098

spring:
  application:
    name: USER-SERVICE
  cloud:
    config:
      server:
        git:
          uri: https://github.com/balaji-seshadri/microservice-tutorial-config

eureka:
  client:
    serviceUrl:
      defaultZone: http://eureka-server:8761/eureka/
    fetch-registry: true
    register-with-eureka: true   
  instance:
    instance-id: ${spring.application.name}:${random.value}
    preferIpAddress: true

# CONSOLIDATED MANAGEMENT BLOCK
management:
  endpoints:
    web:
      exposure:
        include: "health,info,circuitbreakers" # Use quotes to be safe
  endpoint:
    health:
      show-details: always
    circuitbreakers:
      enabled: true
  health:
    circuitbreakers:
      enabled: true
  info:
    env:
      enabled: true    # Required to show properties starting with "info.*"
    java:
      enabled: true    # Optional: shows Java version info
    build:
      enabled: true    # Optional: shows build version from Maven/Gradle      

resilience4j:
  circuitbreaker:
    instances:
      ratingHotelBreaker:
        registerHealthIndicator: true
        slidingWindowSize: 10
        failureRateThreshold: 50
        minimumNumberOfCalls: 5
        waitDurationInOpenState: 6s
        permittedNumberOfCallsInHalfOpenState: 3
        automaticTransitionFromOpenToHalfOpenEnabled: true
        eventConsumerBufferSize: 10
