spring:
  application:
    name: Default-Prod
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka

  instance:
    preferIpAddress: true
    fetch-registry: true
    register-with-eureka: true
